# Generated by Django 5.2.17 on 2026-09-28 15:20

import apps.artworks.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='height',
            field=models.PositiveIntegerField(verbose_name='ارتفاع (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='main_image',
            field=models.ImageField(upload_to='artworks/main/', validators=[apps.artworks.validators.validate_artwork_image]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='technique',
            field=models.CharField(max_length=100, verbose_name='تکنیک'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.PositiveIntegerField(verbose_name='عرض (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year_created',
            field=models.PositiveIntegerField(verbose_name='سال خلق'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(upload_to='artworks/gallery/', validators=[apps.artworks.validators.validate_artwork_image]),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
